### ISSUE TITLE
Binder running broken - AttributeError: Can't get attribute 'Tuple' on <module 'fastcore.utils'

### ISSUE THREAD

**Issue by robmarkcole** [fastai/bear_voila#3]
On launching with binder the following occurs:

<img width="815" alt="image" src="https://user-images.githubusercontent.com/11855322/90984445-e33ee500-e56c-11ea-881e-0498ffc704cc.png">

Presumably related to recent update from fastai1 -> fastai2

Referenced in https://forums.fast.ai/t/voila-does-not-work-for-me/67611/3

Running in locally in debug mode the error raised at `learn_inf = load_learner(path/'export.pkl', cpu=True)` is `AttributeError: Can't get attribute 'Tuple' on <module 'fastcore.utils'`  which is raised at `res = torch.load('export.pkl', map_location='cpu')`

Therefore I think this may actually be an issue on `load_learner`

Note `torch.__version__` = 1.6.0

**Comment by robmarkcole** [comment]
Probable solution https://github.com/fastai/fastai/issues/2666#issuecomment-679164820

**Comment by jph00** [comment]
Fixed.
